---

services:
  mcpo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: ${CONTAINER_NAME}
    user: ${CONTAINER_USER}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - CONFIG_PATH=${CONFIG_PATH}
      - LOG_PATH=${LOG_PATH}
    command: ["--port", "${PORT}", "--api-key", "${API_KEY}", "--config", "${CONFIG_PATH}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mcpo-net

networks:
  mcpo-net:
    driver: bridge