---

services:
  mcpo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: ${CONTAINER_NAME}
    user: root
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - CONFIG_PATH=${CONFIG_PATH}
      - LOG_PATH=${LOG_PATH}
    command: ["--host", "0.0.0.0", "--port", "${PORT}", "--config", "/app/config/config.json", "--api-key", "${API_KEY}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mcpo-net

networks:
  mcpo-net:
    driver: bridge
